// flow-typed signature: 69dd246b65a9cf8c3a13b440c3b274c4
// flow-typed version: <<STUB>>/react-lazy-load_v^3.0.10/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-lazy-load'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-lazy-load' {
	declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-lazy-load/dist/LazyLoad' {
	declare module.exports: any
}

declare module 'react-lazy-load/dist/LazyLoad.min' {
	declare module.exports: any
}

declare module 'react-lazy-load/lib/LazyLoad' {
	declare module.exports: any
}

declare module 'react-lazy-load/lib/utils/__mocks__/getElementPosition' {
	declare module.exports: any
}

declare module 'react-lazy-load/lib/utils/getElementPosition' {
	declare module.exports: any
}

declare module 'react-lazy-load/lib/utils/inViewport' {
	declare module.exports: any
}

declare module 'react-lazy-load/lib/utils/parentScroll' {
	declare module.exports: any
}

// Filename aliases
declare module 'react-lazy-load/dist/LazyLoad.js' {
	declare module.exports: $Exports<'react-lazy-load/dist/LazyLoad'>
}
declare module 'react-lazy-load/dist/LazyLoad.min.js' {
	declare module.exports: $Exports<'react-lazy-load/dist/LazyLoad.min'>
}
declare module 'react-lazy-load/lib/LazyLoad.js' {
	declare module.exports: $Exports<'react-lazy-load/lib/LazyLoad'>
}
declare module 'react-lazy-load/lib/utils/__mocks__/getElementPosition.js' {
	declare module.exports: $Exports<
		'react-lazy-load/lib/utils/__mocks__/getElementPosition'
	>
}
declare module 'react-lazy-load/lib/utils/getElementPosition.js' {
	declare module.exports: $Exports<
		'react-lazy-load/lib/utils/getElementPosition'
	>
}
declare module 'react-lazy-load/lib/utils/inViewport.js' {
	declare module.exports: $Exports<'react-lazy-load/lib/utils/inViewport'>
}
declare module 'react-lazy-load/lib/utils/parentScroll.js' {
	declare module.exports: $Exports<'react-lazy-load/lib/utils/parentScroll'>
}
